spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://39.104.142.92:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&serverTimezone=GMT%2B8&failOverReadOnly=false
    username: root
    password: 123456
  redis:
    database: 2  # Redis数据库索引（默认为0）
    host: 39.104.100.138
    jedis:
      pool:
        max-active: -1  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8  #连接池中的最大空闲连接
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0  # 连接池中的最小空闲连接
    password: 123456
    port: 6379
    timeout: 0  # 连接超时时间（毫秒）
  cloud:
    nacos:
      discovery:
        server-addr: 39.104.100.138:8848

# 日志配置
logging:
  level:
    com.yxt: debug
    org.mybatis: debug
    org.springframework: warn

image:
  upload:
    path: D:\yyd\upload\
  url:
    prefix: http://39.104.100.138:8111/upload/